name: food_recipe_relaxy
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #FOR MODEL
  json_annotation: 4.9.0
  freezed_annotation: 2.4.1

  cupertino_icons: 1.0.8
  dio: 5.4.3+1
  flutter_svg: 2.0.10+1
  google_fonts: 6.2.1
  get: 4.6.6
  flutter_screenutil: 5.9.0
  get_storage: 2.1.1
  flutter_widget_from_html_core: 0.14.12
  cached_network_image: 3.3.1
  lottie: 3.1.0

dev_dependencies:
  change_app_package_name: 1.1.0
  flutter_test:
    sdk: flutter

  #FOR MODEL
  freezed: 2.5.2
  build_runner: 2.4.9
  json_serializable: 6.8.0

  flutter_lints: 3.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/